export const ActionType = {
  CHANGE_CITY: `CHANGE_CITY`,
  CHANGE_HOVERED_OFFER_ID: `CHANGE_HOVERED_OFFER_ID`,
  CHANGE_SORT_TYPE: `CHANGE_SORT_TYPE`,
  OFFERS_LOADING_START: `OFFERS_LOADING_START`,
  OFFERS_LOADING_FAIL: `OFFERS_LOADING_FAIL`,
  OFFERS_LOADING_SUCCESS: `OFFERS_LOADING_SUCCESS`,
  REVIEWS_LOADING_START: `REVIEWS_LOADING_START`,
  REVIEWS_LOADING_FAIL: `REVIEWS_LOADING_FAIL`,
  REVIEWS_LOADING_SUCCESS: `REVIEWS_LOADING_SUCCESS`,
  NEAR_OFFERS_LOADING_START: `NEAR_OFFERS_LOADING_START`,
  NEAR_OFFERS_LOADING_FAIL: `NEAR_OFFERS_LOADING_FAIL`,
  NEAR_OFFERS_LOADING_SUCCESS: `NEAR_OFFERS_LOADING_SUCCESS`,
  SEND_AUTHORIZATION_REQUEST: `SEND_AUTHORIZATION_REQUEST`,
  AUTHORIZATION_SUCCESS: `AUTHORIZATION_SUCCESS`,
  AUTHORIZATION_FAIL: `AUTHORIZATION_FAIL`,
  SET_USER_LOGIN_PROFILE: `SET_USER_LOGIN_PROFILE`,
  REDIRECT_TO_ROUTE: `REDIRECT_TO_ROUTE`
};
